package testpkg;

// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.time.Duration;

/**
 * @author Panagiotis Drakos
 * Student Id: L00170565
 * Selenium Testing
 */
public class TC2_Login {
    private WebDriver driver;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;

    }
    @After
    public void tearDown() {
        driver.close();
        driver.quit();
    }
    @Test
    public void first_case() throws InterruptedException {
        // Manage Web Browser timeouts
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
        driver.manage().timeouts().scriptTimeout(Duration.ofMinutes(2));
        driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(10));

        //driver.get("https://google.com");
        driver.navigate().to("https://google.com");
        String mainWindow = driver.getWindowHandle(); // Manage windows in browser

        driver.navigate().to("http://demo.guru99.com/test/newtours/index.php");
        driver.manage().window().setSize(new Dimension(1536, 901));
        driver.findElement(By.name("userName")).sendKeys("admin");
        Thread.sleep(2000); // Wait statements for demo purposes. Throws Exception in main function
        driver.findElement(By.name("password")).sendKeys("admin");
        driver.findElement(By.name("submit")).click();
        Thread.sleep(2000); // Wait statements for demo purposes. Throws Exception in main function
        driver.findElement(By.linkText("SIGN-OFF")).click();
    }
}